### PR TITLE
Update and add timings bayes parameter estimation

### PR DESCRIPTION
**Pull request by Vaibhavdixit02**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
update the built version?

**Comment by Vaibhavdixit02** [comment]
Yes will do, waiting on a few releases, still stuck in dependency hell.

**Comment by ChrisRackauckas** [comment]
What releases?

**Comment by Vaibhavdixit02** [comment]
https://github.com/JuliaNLSolvers/OptimBase.jl/pull/12 this is the current blocker

**Comment by ChrisRackauckas** [comment]
Dependencies should be fixed now?

**Pull request merged**
