### PR TITLE
Split project tomls

### PR DESCRIPTION
**Pull request by ChrisRackauckas**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
well, let's stress test the system? @christopher-dG is there a nice way to rebuild by folder?

**Comment by christopher-dG** [comment]
Currently no, on two levels:

- We don't have a way to trigger a rebuild for all files in a folder. It would be pretty easy to implement naively, but it would be most reliable and practical if it spawned N jobs that each pushed to the same branch, instead of 1 job or N branches.
- The assumption is currently that we're only ever building off of master. Do you think it would be useful to be able to run "check" jobs that build from a separate branch but don't PR?

**Comment by christopher-dG** [comment]
Okay so I've been thinking about how we can fit all these use cases and maybe this is a decent API:

- `!rebuild <folder>`: Rebuild all tutorials in this folder by creating a new branch, then creating N commits that each update one tutorial.
- `!rebuild <folder>/<file>`: Rebuild one tutorial.
- `!rebuild`: Rebuild one random tutorial.

To choose the branch to build from:

- If the comment is made in a PR, build from that PR branch 
- If the comment is made in an issue, build from master 

To choose the branch to push to:

- If the comment is made in a PR that was automatically opened, push to that same branch
- If the comment is made in an issue, push to a random branch

So to test this PR, you would do:

```
!rebuild folder=introduction
```

How does this sound? Does it cover all the bases?

**Comment by ChrisRackauckas** [comment]
>If the comment is made in a PR that was automatically opened, push to that same branch

Why not in any PR?

**Comment by christopher-dG** [comment]
I guess that's not a bad idea either. So if we were to do it in this one, this PR would be updated to also include changes from the rebuilt tutorials?

**Comment by ChrisRackauckas** [comment]
yeah, it would be nice since usually I don't want to take the time to rebuild locally.

**Pull request merged**
