### PR TITLE
Add DiffEqBayes tutorial markdown, script, html and notebook

### PR DESCRIPTION
**Pull request by Vaibhavdixit02**

### CODE REVIEW

**Comment by Vaibhavdixit02** [comment]
I think the `ω` causes pdf to not build, do you want to change that or keep these and be done with it?

**Comment by ChrisRackauckas** [comment]
We can change the name if it helps.

**Comment by ChrisRackauckas** [comment]
try to isolate to a Weave issue though.

**Comment by Vaibhavdixit02** [comment]
It's there https://github.com/JunoLab/Weave.jl/issues/250. I like it the way it is, if needed one can always change and weave a pdf so..

**Comment by ChrisRackauckas** [comment]
alright

**Pull request merged**
