### PR TITLE
Classical Physics tutorial improvements

### PR DESCRIPTION
**Pull request by SebastianM-C**
Hello! I made a couple of changes to the Classical Physics tutorial.
- Show explicitly how to transform a second order ODE to a system of first order ODEs.
- Add Simple Harmonic Oscillator
- Move the equations to the top for double pendulum
- Improve Poincaré section description
- Prettier Poincaré section for double pendulum (remove artifacts)

I would also want to change the sections a bit (move First order linear ODE above Radioactive Decay of Carbon-14 and similar things, to go from general to particular).

When weaving the files (to html) I get the following error at the end
```julia
ERROR: KeyError: key :folder not found
```
~I'm not sure if that matters.~ Edit: It does not.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Looks great! Can you add the weaved files?

**Comment by SebastianM-C** [comment]
Do you have any preference regarding the organization, or I can reorder as mentioned?

> Can you add the weaved files?
I'm not sure how to generate them correctly. Is it from tests?

**Comment by ChrisRackauckas** [comment]
feel free to reorder it. I don't have much of a preference there.

**Comment by SebastianM-C** [comment]
>I'm not sure how to generate them correctly.

I just saw in the README, sorry for the noise.

**Comment by SebastianM-C** [comment]
Added the weaved files. I think there may be some minor things left (check for typos), but in principle this should be ready for review.

**Pull request merged**
