### PR TITLE
[WIP]Debug errors in Kolmogorov Equations model

### PR DESCRIPTION
**Pull request by ashutosh-b-b**

### CODE REVIEW

**Comment by ashutosh-b-b** [comment]
@ChrisRackauckas This should be able to compile on a GPU.  It will however give an error for some blocks and take a lot of time to compile over the CPU.

**Comment by ChrisRackauckas** [comment]
> It will however give an error for some blocks

What do you mean?

**Comment by ashutosh-b-b** [comment]
> > It will however give an error for some blocks
> 
> What do you mean?

It will give error if it is compiled on the CPU.

**Comment by ChrisRackauckas** [comment]
what's the error?

**Comment by ChrisRackauckas** [comment]
we should make sure it runs on both (and probably start upgrading some stuff to CUDA.jl when it's ready). https://juliagpu.gitlab.io/CUDA.jl/installation/conditional/ should be all we need.

**Comment by ashutosh-b-b** [comment]
@ChrisRackauckas This should be fine ?

**Comment by ChrisRackauckas** [comment]
Does CUDA.jl not interfere with Zygote versioning?

**Comment by ashutosh-b-b** [comment]
You mean while adding? It added alright.

**Pull request merged**
